# Generated by Django 4.0.4 on 2022-04-14 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('key', models.PositiveSmallIntegerField(verbose_name='Key')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstrarct')),
                ('keywords', models.TextField(verbose_name="Kalit so'zlar")),
                ('references', models.TextField(verbose_name='Foydalanilgan adabiyotlar')),
                ('file', models.FileField(max_length=255, upload_to=frontend.models.user_directory_path, verbose_name='Fayl')),
                ('payed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_analyst', to=settings.AUTH_USER_MODEL, verbose_name='Tahlilchi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.category', verbose_name='Kategoriya')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_editor', to=settings.AUTH_USER_MODEL, verbose_name='Taxrirchi')),
                ('state_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_state_analysis', to='backend.state')),
                ('state_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_state_edit', to='backend.state')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
