# Generated by Django 4.0.4 on 2022-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type_menu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
