# Generated by Django 4.0.4 on 2022-10-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0010_myresendarticle_status'),
        ('user_app', '0002_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='my_resend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.myresendarticle'),
        ),
    ]
