# Generated by Django 4.0.4 on 2022-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_notification_my_resend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Tekshirildi', 'tekshirildi'), ('Tekshirilmadi', 'tekshirilmadi'), ('Tekshirilmoqda', 'tekshirilmoqda')], default='Tekshirilmadi', max_length=50),
        ),
    ]
