# Generated by Django 4.0.4 on 2022-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_birthday_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Tugilgan kun'),
        ),
    ]
