# Generated by Django 4.0.4 on 2022-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_tr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
