# Generated by Django 4.0.4 on 2022-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_user_position_remove_user_work_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
