# Generated by Django 4.0.4 on 2022-05-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_user_author_order_user_work_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author_order',
        ),
    ]
