# Generated by Django 4.0.4 on 2022-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_remove_user_author_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_place',
        ),
    ]
