# Generated by Django 4.0.4 on 2022-05-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_user_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='allow_analyst',
            field=models.BooleanField(default=False, verbose_name='Tahlilchi'),
        ),
        migrations.AddField(
            model_name='menu',
            name='allow_editor_chief',
            field=models.BooleanField(default=False, verbose_name='Bosh muharrir'),
        ),
        migrations.AddField(
            model_name='menu',
            name='allow_responsible',
            field=models.BooleanField(default=False, verbose_name='Maul kotib'),
        ),
        migrations.AddField(
            model_name='menu',
            name='allow_user',
            field=models.BooleanField(default=False, verbose_name='User'),
        ),
    ]
