# Generated by Django 4.0.4 on 2022-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_menu_allow_analyst_menu_allow_editor_chief_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='allow_analyst',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='allow_editor_chief',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='allow_responsible',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='allow_user',
        ),
        migrations.AddField(
            model_name='menu',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='alled_role_menus', to='user_app.role'),
        ),
    ]
