# Generated by Django 4.0.4 on 2022-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_menu_allowed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='allowed_role_menus', to='user_app.role'),
        ),
    ]
