# Generated by Django 4.0.4 on 2022-05-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0007_page_name'),
        ('user_app', '0013_alter_menu_allowed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.article'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='allowed_role_menus', to='user_app.role'),
        ),
    ]
