# Generated by Django 4.0.4 on 2022-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_notification_article_alter_menu_allowed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[(0, "O'qilmadi"), (1, "O'qildi")], default="O'qilmadi", max_length=50),
        ),
    ]
