# Generated by Django 4.0.4 on 2022-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[("O'qilmadi", "O'qilmadi"), ("O'qildi", "O'qildi")], max_length=50, null=True),
        ),
    ]
