# Generated by Django 4.0.4 on 2022-05-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_menu_allowed_roles'),
        ('user_app', '0018_alter_notification_status'),
    ]

    operations = [
    ]
