# Generated by Django 4.0.4 on 2022-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_merge_20220526_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='from_user_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_user_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Read', 'read'), ('Unread', 'unread')], default='Unread', max_length=50),
        ),
    ]
