# Generated by Django 4.0.4 on 2022-06-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_remove_notification_from_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
    ]
