# Generated by Django 4.0.4 on 2022-05-16 04:56

import article_app.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0010_remove_user_work_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstrarct')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name="Kalit so'zlar")),
                ('references', models.TextField(blank=True, null=True, verbose_name='Foydalanilgan adabiyotlar')),
                ('file', models.FileField(max_length=255, upload_to=article_app.models.user_directory_path, verbose_name='Fayl')),
                ('payed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_analyst', to=settings.AUTH_USER_MODEL, verbose_name='Tahlilchi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('key', models.PositiveSmallIntegerField(verbose_name='Key')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('midlle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('work_place', models.CharField(max_length=255, verbose_name='Ish joy')),
                ('author_order', models.PositiveSmallIntegerField(default=0)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.article')),
            ],
            options={
                'verbose_name': 'Aftor',
                'verbose_name_plural': 'Aftorlar',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.category', verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_editor', to=settings.AUTH_USER_MODEL, verbose_name='Taxrirchi'),
        ),
        migrations.AddField(
            model_name='article',
            name='state_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_state_analysis', to='user_app.state'),
        ),
        migrations.AddField(
            model_name='article',
            name='state_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_state_edit', to='user_app.state'),
        ),
    ]
