# Generated by Django 4.0.4 on 2022-09-12 10:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('keywords', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('references', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(max_length=255, upload_to='files/articles/', verbose_name='Fayl')),
                ('payed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlankPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BlankPage',
                'verbose_name_plural': 'BlankPages',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('key', models.PositiveSmallIntegerField(verbose_name='Key')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.PositiveBigIntegerField(default=5, unique=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('tag', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='blog/')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.SlugField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
            },
        ),
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='files/jurnals/', verbose_name='Fayl')),
                ('number_magazine', models.PositiveBigIntegerField(default=0, unique=True)),
                ('year_magazine', models.CharField(blank=True, max_length=4)),
                ('img', models.ImageField(default='jurnal_ob.png', upload_to='jurnal/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('article', models.ManyToManyField(blank=True, related_name='articles', to='article_app.article')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('work_place', models.CharField(max_length=255, verbose_name='Ish joy')),
                ('author_order', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.article')),
            ],
            options={
                'verbose_name': 'Aftor',
                'verbose_name_plural': 'Aftorlar',
            },
        ),
    ]
