# Generated by Django 4.0.4 on 2022-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_rename_article_id_authors_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Abstrarct'),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foydalanilgan adabiyotlar'),
        ),
    ]
