# Generated by Django 4.0.4 on 2022-05-10 06:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Abstrarct'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=ckeditor.fields.RichTextField(verbose_name="Kalit so'zlar"),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=ckeditor.fields.RichTextField(verbose_name='Foydalanilgan adabiyotlar'),
        ),
    ]
