# Generated by Django 4.0.4 on 2022-09-16 10:07

import article_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_step'),
        ('article_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='state_analysis',
        ),
        migrations.RemoveField(
            model_name='article',
            name='state_edit',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='extra_author',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to='article_app.authors'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=article_app.models.user_directory_path, verbose_name='PDF Fayl'),
        ),
        migrations.AddField(
            model_name='article',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_state', to='user_app.state'),
        ),
        migrations.AddField(
            model_name='article',
            name='step_bosh_muharrir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_step_boshm', to='user_app.step'),
        ),
        migrations.AddField(
            model_name='article',
            name='step_taqriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_step_taq', to='user_app.step'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=article_app.models.user_directory_path, verbose_name='Word Fayl'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
