# Generated by Django 4.0.4 on 2022-05-10 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_alter_article_abstract_alter_article_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shartnoma',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Kalit so'zlar"),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Foydalanilgan adabiyotlar'),
        ),
    ]
