# Generated by Django 4.0.4 on 2022-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_remove_article_state_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='extra_author',
            field=models.ManyToManyField(blank=True, related_name='authors', to='article_app.authors'),
        ),
    ]
