# Generated by Django 4.0.4 on 2022-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_alter_article_abstract_alter_article_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Abstrarct'),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='Foydalanilgan adabiyotlar'),
        ),
    ]
