# Generated by Django 4.0.4 on 2022-09-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_alter_article_extra_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='extra_author',
        ),
        migrations.AddField(
            model_name='authors',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.article'),
        ),
    ]
