# Generated by Django 4.0.4 on 2022-05-10 06:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_article_shartnoma_alter_article_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('shartnoma', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='shartnoma',
        ),
    ]
