# Generated by Django 4.0.4 on 2022-09-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_remove_article_extra_author_authors_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyResendArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_app.article')),
            ],
        ),
    ]
