# Generated by Django 4.0.4 on 2022-09-19 11:11

import article_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_step'),
        ('article_app', '0006_myresendarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='message',
        ),
        migrations.AddField(
            model_name='myresendarticle',
            name='file_word',
            field=models.FileField(blank=True, max_length=255, upload_to=article_app.models.user_directory_path, verbose_name='Word Fayl'),
        ),
        migrations.AddField(
            model_name='myresendarticle',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='myresendarticle',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.state'),
        ),
    ]
