# Generated by Django 4.0.4 on 2022-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0006_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
