# Generated by Django 4.0.4 on 2022-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='oreder',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
