# Generated by Django 4.0.4 on 2022-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0007_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_magazine', models.PositiveBigIntegerField(default=0, unique=True)),
                ('year_magazine', models.CharField(blank=True, max_length=4)),
                ('order_article', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('article', models.ManyToManyField(blank=True, related_name='articles', to='article_app.article')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
            },
        ),
    ]
