# Generated by Django 4.0.4 on 2022-06-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0008_magazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='order_article',
        ),
    ]
