# Generated by Django 4.0.4 on 2022-10-04 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_app', '0008_alter_myresendarticle_file_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='myresendarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_resend_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
