# Generated by Django 4.0.4 on 2022-06-20 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0009_remove_magazine_order_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
