# Generated by Django 4.0.4 on 2022-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0010_alter_article_abstract_alter_article_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
