# Generated by Django 4.0.4 on 2022-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0011_rename_magazine_journal_delete_page_delete_shartnoma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='article_app.category', verbose_name='Kategoriya'),
        ),
    ]
