# Generated by Django 4.0.4 on 2022-06-24 12:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0011_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
