# Generated by Django 4.0.4 on 2022-05-13 11:57

import article_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0012_alter_article_file_alter_article_state_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(max_length=255, upload_to=article_app.models.user_directory_path, verbose_name='Fayl'),
        ),
    ]
