# Generated by Django 4.0.4 on 2022-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0013_magazine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
