# Generated by Django 4.0.4 on 2022-06-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0014_article_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='description',
        ),
    ]
