# Generated by Django 4.0.4 on 2022-06-29 07:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0015_remove_magazine_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_pulish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
                'ordering': ['-id'],
            },
        ),
    ]
