# Generated by Django 4.0.4 on 2022-06-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0016_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_pulish',
            new_name='is_publish',
        ),
    ]
