# Generated by Django 4.0.4 on 2022-06-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0017_rename_is_pulish_post_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=1, upload_to='blog/'),
            preserve_default=False,
        ),
    ]
