# Generated by Django 4.0.4 on 2022-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0018_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
