# Generated by Django 4.0.4 on 2022-07-13 10:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0019_post_url_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BlankPage',
                'verbose_name_plural': 'BlankPages',
            },
        ),
    ]
