# Generated by Django 4.0.4 on 2022-07-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0020_blankpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='jurnal/'),
        ),
    ]
